# Generated by Django 2.0.5 on 2018-06-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp18', '0002_auto_20180522_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='warehouse',
            field=models.CharField(default='Windsor', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=True, max_length=200, null=True),
        ),
    ]
